In [3]:
from fyers_apiv3 import fyersModel
from fyers_apiv3.FyersWebsocket import data_ws
import pandas as pd
# Replace these values with your actual API credentials
client_id = "PP860PBEU0-100"
secret_key = "JC501DPXH7"
redirect_uri = "https://google.com"
response_type = "code"  
state = "sample_state"

# Create a session model with the provided credentials
session = fyersModel.SessionModel(
    client_id=client_id,
    secret_key=secret_key,
    redirect_uri=redirect_uri,
    response_type=response_type
)
# Generate the auth code using the session model
response = session.generate_authcode()

# Print the auth code received in the response
print(response)

https://api-t1.fyers.in/api/v3/generate-authcode?client_id=PP860PBEU0-100&redirect_uri=https%3A%2F%2Fgoogle.com&response_type=code&state=None

In [4]:
auth_code = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJhcGkubG9naW4uZnllcnMuaW4iLCJpYXQiOjE2OTkyNzczMzIsImV4cCI6MTY5OTMwNzMzMiwibmJmIjoxNjk5Mjc2NzMyLCJhdWQiOiJbXCJ4OjBcIiwgXCJ4OjFcIiwgXCJ4OjJcIiwgXCJkOjFcIiwgXCJkOjJcIiwgXCJ4OjFcIiwgXCJ4OjBcIl0iLCJzdWIiOiJhdXRoX2NvZGUiLCJkaXNwbGF5X25hbWUiOiJYUzk4MzY4Iiwib21zIjoiSzEiLCJoc21fa2V5IjoiYmIyM2YxMjg2ODFiNGE3OWM2NmU2MTM4MDdkNjZhNGM5NmE5MjUzNDZhYjhiZWRkYzQ0MDdmMzYiLCJub25jZSI6IiIsImFwcF9pZCI6IlBQODYwUEJFVTAiLCJ1dWlkIjoiOTYyODNmZmQyOWU0NDc1ODhhZjA2ZWJmNTgwOTEzMjYiLCJpcEFkZHIiOiIwLjAuMC4wIiwic2NvcGUiOiIifQ.CDZ1AConZfXVenNfxHn9IWfWsFPMbhhg-5KUADZb5YY"

In [5]:
grant_type = "authorization_code"
# Create a session object to handle the Fyers API authentication and token generation
session = fyersModel.SessionModel(
    client_id=client_id,
    secret_key=secret_key, 
    redirect_uri=redirect_uri, 
    response_type=response_type, 
    grant_type=grant_type
)
# Set the authorization code in the session object
session.set_token(auth_code)

# Generate the access token using the authorization code
response = session.generate_token()

# Print the response, which should contain the access token and other details
print(response)

{'s': 'ok', 'code': 200, 'message': '', 'access_token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJhcGkuZnllcnMuaW4iLCJpYXQiOjE2OTkyNzczNjIsImV4cCI6MTY5OTMxNzAyMiwibmJmIjoxNjk5Mjc3MzYyLCJhdWQiOlsieDowIiwieDoxIiwieDoyIiwiZDoxIiwiZDoyIiwieDoxIiwieDowIl0sInN1YiI6ImFjY2Vzc190b2tlbiIsImF0X2hhc2giOiJnQUFBQUFCbFNPb3lSNGxwUGk0YzNCOHNjeTVxNmVrOWZaendBMTlHV19teG91Z2RubXEyUmVPUWpvamc1NElxUTJuUDNxWE5DVk5RSTFnd090WGtZVU9sM19JNXdFWlVHZWZxMkNJSEJVRmhiOE54dHlFSTNvcz0iLCJkaXNwbGF5X25hbWUiOiJTQU5TS0FSIFNSSVZBU1RBVkEiLCJvbXMiOiJLMSIsImhzbV9rZXkiOiJiYjIzZjEyODY4MWI0YTc5YzY2ZTYxMzgwN2Q2NmE0Yzk2YTkyNTM0NmFiOGJlZGRjNDQwN2YzNiIsImZ5X2lkIjoiWFM5ODM2OCIsImFwcFR5cGUiOjEwMCwicG9hX2ZsYWciOiJOIn0.zkkp5pSY2s3pfKmbfvgYGVoZmLT52yPux6RVHlXfOBY', 'refresh_token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJhcGkuZnllcnMuaW4iLCJpYXQiOjE2OTkyNzczNjIsImV4cCI6MTcwMDUyNjYyMiwibmJmIjoxNjk5Mjc3MzYyLCJhdWQiOlsieDowIiwieDoxIiwieDoyIiwiZDoxIiwiZDoyIiwieDoxIiwieDowIl0sInN1YiI6InJlZnJlc2hfdG9rZW4iLCJhdF9oYXNoIjoiZ0FBQUFBQmxTT295UjRscFBpNGMzQjhzY3k1cTZlazlmWnp3QTE5R1dfbXhvdWdkbm1xMlJlT1Fqb2pnNTRJcVEyblAzcVhOQ1ZOUUkxZ3dPdFhrWVVPbDNfSTV3RVpVR2VmcTJDSUhCVUZoYjhOeHR5RUkzb3M9IiwiZGlzcGxheV9uYW1lIjoiU0FOU0tBUiBTUklWQVNUQVZBIiwib21zIjoiSzEiLCJoc21fa2V5IjoiYmIyM2YxMjg2ODFiNGE3OWM2NmU2MTM4MDdkNjZhNGM5NmE5MjUzNDZhYjhiZWRkYzQ0MDdmMzYiLCJmeV9pZCI6IlhTOTgzNjgiLCJhcHBUeXBlIjoxMDAsInBvYV9mbGFnIjoiTiJ9.fGlcP8ISWMiYQ7RmrqCwpGPgEhHLW-jXggXf1TejWZ0'}

In [6]:
df=pd.DataFrame()
df=response
tk=df['access_token']
print(tk)

eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJhcGkuZnllcnMuaW4iLCJpYXQiOjE2OTkyNzczNjIsImV4cCI6MTY5OTMxNzAyMiwibmJmIjoxNjk5Mjc3MzYyLCJhdWQiOlsieDowIiwieDoxIiwieDoyIiwiZDoxIiwiZDoyIiwieDoxIiwieDowIl0sInN1YiI6ImFjY2Vzc190b2tlbiIsImF0X2hhc2giOiJnQUFBQUFCbFNPb3lSNGxwUGk0YzNCOHNjeTVxNmVrOWZaendBMTlHV19teG91Z2RubXEyUmVPUWpvamc1NElxUTJuUDNxWE5DVk5RSTFnd090WGtZVU9sM19JNXdFWlVHZWZxMkNJSEJVRmhiOE54dHlFSTNvcz0iLCJkaXNwbGF5X25hbWUiOiJTQU5TS0FSIFNSSVZBU1RBVkEiLCJvbXMiOiJLMSIsImhzbV9rZXkiOiJiYjIzZjEyODY4MWI0YTc5YzY2ZTYxMzgwN2Q2NmE0Yzk2YTkyNTM0NmFiOGJlZGRjNDQwN2YzNiIsImZ5X2lkIjoiWFM5ODM2OCIsImFwcFR5cGUiOjEwMCwicG9hX2ZsYWciOiJOIn0.zkkp5pSY2s3pfKmbfvgYGVoZmLT52yPux6RVHlXfOBY

In [7]:
fyers = fyersModel.FyersModel(client_id=client_id, is_async=False, token=tk, log_path="")

In [12]:
def signal_generator(df):
    Open = df.open.iloc[-1]
    Close = df.close.iloc[-1]
    previous_Open = df.open.iloc[-2]
    previous_Close = df.close.iloc[-2]
    
    # red candle
    if (Open>Close):
        return 1

    # green candle
    elif (Open<Close):
        return 2
    
    # No clear pattern
    else:
        return 0

In [13]:

call=input(str("Enter the symbol for call :"))
put=input(str("Enter the symbol for put :"))
calltight=int(input("Enter qty for tight lots for call option:  "))
callspare=int(input("Enter qty for spare lots for call option:  "))
puttight=int(input("Enter qty for tight lots for put option:  "))
putspare=int(input("Enter qty for spare lots for put option:  "))

Enter the symbol for call :NSE:BANKNIFTY23N0843100CE
Enter the symbol for put :NSE:BANKNIFTY23N0843600PE
Enter qty for tight lots for call option:  5
Enter qty for spare lots for call option:  5
Enter qty for tight lots for put option:  5
Enter qty for spare lots for put option:  5

In [31]:
def get_datacall():
    data = {
    "symbol":call,
    "resolution":"5",
    "date_format":"1",
    "range_from":"2023-11-02",
    "range_to":"2023-11-08",
    "cont_flag":"1"}

    hdata=fyers.history(data=data)
    df = pd.DataFrame.from_dict(hdata['candles'])
    cols = ['datetime','open','high','low','close','volume']
    df.columns=cols
    df['datetime']= pd.to_datetime(df['datetime'],unit="s")
    df['datetime'] = df['datetime'].dt.tz_localize('utc').dt.tz_convert('Asia/Kolkata')
    df['datetime'] = df['datetime'].dt.tz_localize(None)
    df['date'] = df['datetime'].dt.date
    df['time'] = df['datetime'].dt.time
    
    signal = []
    signal.append(0)
    for i in range(1,len(df)):
        dataF = df[i-1:i+1]
        signal.append(signal_generator(dataF))
    #signal_generator(data)
    df["signal"] = signal
    
    goodpair = pd.DataFrame(columns=['Date', 'Time', 'HC', 'LC'])
    #print(goodpairCE)
    
    for i in range(1,len(df)):
        h=0
        l=0
        t=0
        signalfirst = df.signal.iloc[i]
        signalsecond = df.signal.iloc[i-1]
        presenthigh = df.high.iloc[i]
        previoushigh = df.high.iloc[i-1]
        presentlow = df.low.iloc[i]
        previouslow = df.low.iloc[i-1]
        previoustime = df.time.iloc[i-1]
        presenttime = df.time.iloc[i]
        previousdate = df.date.iloc[i-1]
        presentdate = df.date.iloc[i]
    
        #goodpair
        if(signalfirst!=signalsecond):
            if(previoushigh>presenthigh and presentlow<previouslow):
                h = previoushigh
                l = presentlow
                t=1
            elif(previoushigh<presenthigh and presentlow>previouslow):
                h = presenthigh
                l = previouslow
                t=1
        if(abs(h-l)>=0 and abs(h-l)<=30 and t==1):
            goodpair.loc[len(goodpair)] = [previousdate, previoustime, h, l]
    global goodpairCE
    goodpairCE=goodpair
    #return goodpairCE

In [32]:
get_datacall()
goodpairCE

          Date      Time      HC      LC
0   2023-11-02  10:00:00  393.55  363.60
1   2023-11-02  10:40:00  321.30  302.50
2   2023-11-02  10:55:00  296.30  276.40
3   2023-11-02  11:10:00  312.35  292.00
4   2023-11-02  11:20:00  298.45  278.25
5   2023-11-02  12:00:00  194.00  178.95
6   2023-11-02  12:35:00  212.85  192.45
7   2023-11-02  12:45:00  207.90  196.85
8   2023-11-02  13:10:00  227.95  208.00
9   2023-11-02  13:55:00  243.85  216.80
10  2023-11-02  14:15:00  256.15  227.65
11  2023-11-02  14:35:00  248.35  227.70
12  2023-11-03  10:45:00  400.80  378.30
13  2023-11-03  11:25:00  390.00  362.55
14  2023-11-03  11:35:00  400.85  376.30
15  2023-11-03  11:55:00  380.05  365.20
16  2023-11-03  12:15:00  390.60  376.00
17  2023-11-03  12:25:00  387.00  373.00
18  2023-11-03  12:30:00  386.25  373.00
19  2023-11-03  12:40:00  404.40  376.45
20  2023-11-03  12:55:00  373.00  356.50
21  2023-11-03  13:05:00  385.20  363.20
22  2023-11-03  13:10:00  385.20  367.40
23  2023-11-03  14:10:00  397.40  372.30
24  2023-11-03  14:55:00  394.05  366.20
25  2023-11-03  15:10:00  375.55  364.25
26  2023-11-03  15:20:00  382.65  358.35
27  2023-11-06  09:55:00  512.00  492.55
28  2023-11-06  10:00:00  508.80  489.00
29  2023-11-06  10:05:00  500.95  475.30
30  2023-11-06  10:15:00  515.20  490.30
31  2023-11-06  10:20:00  515.20  491.60
32  2023-11-06  10:35:00  501.15  486.95
33  2023-11-06  10:40:00  498.85  479.15
34  2023-11-06  11:45:00  462.70  446.40
35  2023-11-06  12:30:00  484.25  455.00
36  2023-11-06  12:35:00  484.25  463.20
37  2023-11-06  13:15:00  497.05  469.95
38  2023-11-06  13:30:00  497.00  478.45
39  2023-11-06  13:35:00  491.90  477.60
40  2023-11-06  13:50:00  479.25  461.15
41  2023-11-06  14:00:00  495.75  469.30

In [36]:
def get_dataput():
    data = {
    "symbol":put,
    "resolution":"5",
    "date_format":"1",
    "range_from":"2023-11-02",
    "range_to":"2023-11-08",
    "cont_flag":"1"
    }

    hdata=fyers.history(data=data)
    df = pd.DataFrame.from_dict(hdata['candles'])
    cols = ['datetime','open','high','low','close','volume']
    df.columns=cols
    df['datetime']= pd.to_datetime(df['datetime'],unit="s")
    df['datetime'] = df['datetime'].dt.tz_localize('utc').dt.tz_convert('Asia/Kolkata')
    df['datetime'] = df['datetime'].dt.tz_localize(None)
    df['date'] = df['datetime'].dt.date
    df['time'] = df['datetime'].dt.time
    #df.iloc[:,:]
    
    signal = []
    signal.append(0)
    for i in range(1,len(df)):
        dataF = df[i-1:i+1]
        signal.append(signal_generator(dataF))
    #signal_generator(data)
    df["signal"] = signal
    
    goodpair = pd.DataFrame(columns=['Date', 'Time', 'HP', 'LP'])
    
    for i in range(1,len(df)):
        h=0
        l=0
        t=0
        signalfirst = df.signal.iloc[i]
        signalsecond = df.signal.iloc[i-1]
        presenthigh = df.high.iloc[i]
        previoushigh = df.high.iloc[i-1]
        presentlow = df.low.iloc[i]
        previouslow = df.low.iloc[i-1]
        previoustime = df.time.iloc[i-1]
        presenttime = df.time.iloc[i]
        previousdate = df.date.iloc[i-1]
        presentdate = df.date.iloc[i]
    
        #goodpair
        if(signalfirst!=signalsecond):
            if(previoushigh>presenthigh and presentlow<previouslow):
                h = previoushigh
                l = presentlow
                t=1
            elif(previoushigh<presenthigh and presentlow>previouslow):
                h = presenthigh
                l = previouslow
                t=1
        if(abs(h-l)>=0 and abs(h-l)<=30 and t==1):
            goodpair.loc[len(goodpair)] = [previousdate, previoustime, h, l]
    global goodpairPE
    goodpairPE=goodpair
    #return goodpairPE

In [59]:
get_dataput()
goodpairPE

          Date      Time      HP      LP
0   2023-11-02  10:00:00  478.50  453.00
1   2023-11-02  11:20:00  570.15  541.25
2   2023-11-03  10:05:00  403.65  374.50
3   2023-11-03  11:15:00  395.45  365.50
4   2023-11-03  11:20:00  404.60  377.75
5   2023-11-03  11:55:00  408.70  392.00
6   2023-11-03  12:15:00  390.00  375.25
7   2023-11-03  12:25:00  392.50  378.30
8   2023-11-03  12:55:00  408.15  387.60
9   2023-11-03  13:05:00  398.90  374.85
10  2023-11-03  13:10:00  391.75  374.85
11  2023-11-03  14:10:00  379.90  356.85
12  2023-11-03  15:10:00  391.05  376.35
13  2023-11-06  09:20:00  221.90  196.00
14  2023-11-06  09:30:00  220.35  197.65
15  2023-11-06  09:45:00  246.30  220.25
16  2023-11-06  09:55:00  226.55  214.15
17  2023-11-06  10:00:00  229.55  216.40
18  2023-11-06  10:05:00  237.55  220.90
19  2023-11-06  10:10:00  237.55  216.50
20  2023-11-06  10:15:00  227.80  209.65
21  2023-11-06  10:20:00  223.40  209.65
22  2023-11-06  10:35:00  226.35  217.15
23  2023-11-06  10:40:00  233.55  218.30
24  2023-11-06  11:45:00  251.75  237.00
25  2023-11-06  11:55:00  268.15  244.20
26  2023-11-06  13:15:00  223.65  207.75
27  2023-11-06  13:50:00  230.55  216.85
28  2023-11-06  14:00:00  224.25  204.30
29  2023-11-06  14:25:00  176.80  159.40
30  2023-11-06  14:40:00  180.20  160.50
31  2023-11-06  14:45:00  182.65  166.30
32  2023-11-06  15:05:00  157.45  146.40
33  2023-11-06  15:10:00  155.80  146.40

In [67]:
import time
from datetime import date
def onmessage(message):
    t = time.localtime()
    cmin = time.strftime("%M", t)
    csec = time.strftime("%S", t)
    if (int(cmin) % 5 == 0 and int(csec) <9):
        get_datacall()
        get_dataput()
        if (len(goodpairCE)>=1 and goodpairCE.Date.iloc[-1]==date.today()):
            global hc
            hc = goodpairCE.HC.iloc[-1]
            global lc
            lc = goodpairCE.LC.iloc[-1]
        if (len(goodpairPE)>=1 and goodpairPE.Date.iloc[-1]==date.today()):
            global hp
            hp = goodpairPE.HP.iloc[-1]
            global lp
            lp = goodpairPE.LP.iloc[-1]
    if (len(goodpairCE)>=1 and goodpairCE.Date.iloc[-1]==date.today()):
        data_ct = {
            "symbol":call,
            "qty":calltight,
            "type":1,
            "side":1,
            "productType":"BO",
            "limitPrice":0,
            "stopPrice":0,
            "validity":"DAY",
            "disclosedQty":0,
            "offlineOrder":False,
            "stopLoss":lc,
            "takeProfit":hc+15
        }
        response_ct = fyers.place_order(data=data_ct)
        print(f"entry tight slot for call {call}")
        #print(response_ct)
    if (len(goodpairPE)>=1 and goodpairPE.Date.iloc[-1]==date.today()):
        data_pt = {
            "symbol":put,
            "qty":puttight,
            "type":1,
            "side":1,
            "productType":"BO",
            "limitPrice":0,
            "stopPrice":0,
            "validity":"DAY",
            "disclosedQty":0,
            "offlineOrder":False,
            "stopLoss":lp,
            "takeProfit":hp+15
        }
        response_pt = fyers.place_order(data=data_pt)
        print(f"entry tight slot for put {put}")
        #print(response_pt)
    if (len(goodpairCE)>=1 and goodpairCE.Date.iloc[-1]==date.today()):
        data_cs = {
            "symbol":call,
            "qty":callspare,
            "type":1,
            "side":1,
            "productType":"CO",
            "limitPrice":0,
            "stopPrice":0,
            "validity":"DAY",
            "disclosedQty":0,
            "offlineOrder":False,
            "stopLoss":lc,
            "takeProfit":0
        }
        response_cs = fyers.place_order(data=data_cs)
        print(f"entry spare slot for call {call}")
        #print(response_cs)
        target=hc+15
        if(message['symbol']==call and message['ltp']>=target):
            target=target+15
            sl=target-30
            orderId = response_cs['id']
            data_mcs = {
                "id":orderId, 
                "type":1, 
                "limitPrice": sl,
                "qty":callspare
            }
            response_mcs = fyers.modify_order(data=data_mcs)
            print(f"spare slot trailed for call {call} at sl={sl}")
            
    if (len(goodpairPE)>=1 and goodpairPE.Date.iloc[-1]==date.today()):
        data_ps = {
            "symbol":put,
            "qty":putspare,
            "type":1,
            "side":1,
            "productType":"CO",
            "limitPrice":0,
            "stopPrice":0,
            "validity":"DAY",
            "disclosedQty":0,
            "offlineOrder":False,
            "stopLoss":lp,
            "takeProfit":0
        }
        response_ps = fyers.place_order(data=data_ps)
        print(f"entry spare slot for put {put}")
        #print(response_ps)
        target=hp+15
        if(message['symbol']==put and message['ltp']>=target):
            target=target+15
            sl=target-30
            orderId = response_ps['id']
            data_mps = {
                "id":orderId, 
                "type":1, 
                "limitPrice": sl,
                "qty":putspare
            }
            response_mps = fyers.modify_order(data=data_mps)
            print(f"spare slot trailed for put {put} at sl={sl}")

def onerror(message):

    print("Error:", message)


def onclose(message):
  
    print("Connection closed:", message)


def onopen():
    data_type = "SymbolUpdate"
    symbols = [call,put]
    #print(goodpairCE.HC.iloc[-1])
    ofyers.subscribe(symbols=symbols, data_type=data_type)
    ofyers.keep_running()
access_token = client_id + ":" + tk

ofyers = data_ws.FyersDataSocket(
    access_token=access_token,
    log_path="",                     
    litemode=False,
    write_to_file=False,              
    reconnect=True,                 
    on_connect=onopen,               
    on_close=onclose,                
    on_error=onerror,               
    on_message=onmessage             
)
ofyers.connect()

entry tight slot for call NSE:BANKNIFTY23N0843100CE
entry tight slot for put NSE:BANKNIFTY23N0843600PE
entry spare slot for call NSE:BANKNIFTY23N0843100CE
Error: KeyError: The key 'symbol' is missing in the response.
entry tight slot for call NSE:BANKNIFTY23N0843100CE
entry tight slot for put NSE:BANKNIFTY23N0843600PE
entry spare slot for call NSE:BANKNIFTY23N0843100CE
Error: KeyError: The key 'symbol' is missing in the response.
entry tight slot for call NSE:BANKNIFTY23N0843100CE
entry tight slot for put NSE:BANKNIFTY23N0843600PE
entry spare slot for call NSE:BANKNIFTY23N0843100CE
Error: KeyError: The key 'symbol' is missing in the response.